### ISSUE TITLE
Branching L systems with multiple rules

### ISSUE THREAD

**Issue by TIF141** [TIF141/l-systems#17]
Branching L systems with multiple rules seems to give a fractal pattern of the correct result, rather than just the result itself. E.g. examples d, e, f on pg 25.
![Screenshot from 2023-10-25 16-55-23-1](https://github.com/TIF141/l-systems/assets/21172144/35ddd27e-f294-4fb2-bf7a-5bfd5eff7ca0)

**Comment by malonej501** [comment]
Fixed this bug - the coordinates for the lines for each successive iteration were being appended to the history without any indication they were a different iteration. This meant the drawing function was plotting the entire history rather than just the the lines for the last iteration. The angle was also being passed onto subsequent iterations, causing the fractal to spin around.

Solved by clearing the history and the angle after each iteration in generator.py
